/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import CRUD.Database;
import javax.swing.JOptionPane;

/**
 *
 * @author ryand
 */
public class FrameRekamMedis extends javax.swing.JFrame {

    /**
     * Creates new form FrameRekamMedis
     */
    public FrameRekamMedis() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
        SimpanRM.setFocusable(false);
        UbahRM.setFocusable(false);
        HapusRM.setFocusable(false);
        jButton4.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SimpanRM = new javax.swing.JButton();
        UbahRM = new javax.swing.JButton();
        HapusRM = new javax.swing.JButton();
        RMidText = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        judulRMText = new javax.swing.JTextField();
        pasIDText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tglRMText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fileRMText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ketRMText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Tanggal Rekam Medis (YYYY,MM,DD)");

        jLabel5.setText("File Rekam Medis");

        jLabel6.setText("Keterangan Rekam Medis");

        SimpanRM.setText("Simpan");
        SimpanRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanRMActionPerformed(evt);
            }
        });

        UbahRM.setText("Ubah");
        UbahRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahRMActionPerformed(evt);
            }
        });

        HapusRM.setText("Hapus");
        HapusRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusRMActionPerformed(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Rekam Medis");

        jLabel2.setText("ID Pasien");

        jLabel3.setText("Judul Rekam Medis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ketRMText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(fileRMText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tglRMText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judulRMText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pasIDText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RMidText, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SimpanRM)
                        .addGap(18, 18, 18)
                        .addComponent(UbahRM)
                        .addGap(18, 18, 18)
                        .addComponent(HapusRM)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RMidText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(pasIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(judulRMText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tglRMText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(fileRMText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ketRMText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SimpanRM)
                    .addComponent(UbahRM)
                    .addComponent(HapusRM))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimpanRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanRMActionPerformed
        // TODO add your handling code here:
        Database koneksiData = new Database();

        koneksiData.tambahRM(Integer.valueOf(RMidText.getText()),
            Integer.valueOf(pasIDText.getText()),
            judulRMText.getText(),
            tglRMText.getText(),
            fileRMText.getText(),
            ketRMText.getText());
        JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
    }//GEN-LAST:event_SimpanRMActionPerformed

    private void UbahRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahRMActionPerformed
        // TODO add your handling code here:
        Database koneksiData = new Database();

        koneksiData.ubahRM(Integer.valueOf(RMidText.getText()),
            Integer.valueOf(pasIDText.getText()),
            judulRMText.getText(),
            tglRMText.getText(),
            fileRMText.getText(),
            ketRMText.getText());
        JOptionPane.showMessageDialog(null, "Data berhasil di ubah");
    }//GEN-LAST:event_UbahRMActionPerformed

    private void HapusRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusRMActionPerformed
        // TODO add your handling code here:
        Database koneksiData = new Database();

        koneksiData.hapusRM(Integer.valueOf(RMidText.getText()));
        JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
    }//GEN-LAST:event_HapusRMActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRekamMedis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HapusRM;
    private javax.swing.JTextField RMidText;
    private javax.swing.JButton SimpanRM;
    private javax.swing.JButton UbahRM;
    private javax.swing.JTextField fileRMText;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField judulRMText;
    private javax.swing.JTextField ketRMText;
    private javax.swing.JTextField pasIDText;
    private javax.swing.JTextField tglRMText;
    // End of variables declaration//GEN-END:variables
}
